**PROBLEM 1**

question no 1.

In [ ]:
import numpy as np
A=np.empty((2,2))
print(A)

[[4.63516502e-310 0.00000000e+000]
 [9.04115220e+271 1.02124020e+277]]


question no 2.

In [ ]:
import numpy as np
A = np.ones((4,2))
print(A)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


question no 3.

In [ ]:
import numpy as np
filled = np.full((2,2),1)#2*2 matrix filled by 1 as the value
print(filled)

[[1 1]
 [1 1]]


question no 4.

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
zero_arr = np.zeros_like(arr)
print(zero_arr)

[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [0 0 0]]


question no 5.

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
ones_arr = np.ones_like(arr)
print(ones_arr)

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]]


question no 6.

In [ ]:
import numpy as np
new_list=[1,2,3,4,5]
arr = np.array(new_list)
print(arr)

[1 2 3 4 5]


**PROBLEM 2**

question 1

In [ ]:
import numpy as np
arr = np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


question 2

In [ ]:
import numpy as np
arr = np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


question 3

In [ ]:
import numpy as np
arr = np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


question 4

In [ ]:
import numpy as np
arr = np.random.random(30)
print(arr)
arr_mean = arr.mean()
print("\n", arr_mean)

[0.25316571 0.05804136 0.11192424 0.21356917 0.40160648 0.53838875
 0.72341908 0.38931199 0.77118695 0.69403547 0.38982082 0.49589215
 0.43180007 0.57250565 0.82236922 0.72406099 0.12400481 0.22788642
 0.79845947 0.07163072 0.19752169 0.44729177 0.28108827 0.5822033
 0.85789205 0.13603174 0.07938553 0.37773566 0.21468016 0.83295654]

 0.4273288733847763


question 5

In [ ]:
import numpy as np
arr = np.random.random((10,10))
print(arr)
arr_min = arr.min()
arr_max = arr.max()
print("\n", arr_min, arr_max)

[[0.95694992 0.21469665 0.34123915 0.8010515  0.02274428 0.2549822
  0.15958751 0.57089512 0.92552514 0.7462947 ]
 [0.34694739 0.19195436 0.0398015  0.17475267 0.92611159 0.14968315
  0.59069179 0.91818841 0.97608987 0.99674545]
 [0.18343649 0.89990307 0.15720029 0.43872506 0.9099269  0.38547253
  0.61574266 0.48131515 0.49355118 0.8967568 ]
 [0.69208098 0.51866884 0.73149022 0.21876587 0.4358945  0.20594963
  0.96490778 0.2957102  0.72596941 0.98250119]
 [0.83631173 0.2083463  0.47954676 0.6715684  0.78075956 0.74320244
  0.45564489 0.33563334 0.25203191 0.56678889]
 [0.70556833 0.1735209  0.13491861 0.8393214  0.86915787 0.63097178
  0.34190136 0.63856285 0.90693272 0.62405807]
 [0.72041511 0.10751712 0.36615068 0.09596223 0.025117   0.44840899
  0.62020486 0.59082586 0.82624806 0.60088017]
 [0.19949099 0.20435207 0.37848826 0.8092342  0.18708876 0.52282685
  0.25876197 0.36925977 0.21182906 0.8297098 ]
 [0.15910366 0.87292002 0.95319402 0.61846773 0.76036986 0.98025407
  0.41443661 

question 6

In [ ]:
import numpy as np
arr = np.zeros(10)
arr[4] = 1
print (arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


question 7

In [ ]:
import numpy as np
arr = [1,2,0,0,4,0]
rev_arr = np.flip(arr)
print(rev_arr)

[0 4 0 0 2 1]


question 8

In [ ]:
import numpy as np
arr = np.ones((4,4))
print("original array: \n", arr)
arr[1:-1,1:-1] = 0
print("Array with 1 on the border and 0 on inside \n", arr)

original array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array with 1 on the border and 0 on inside 
 [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


question 9

**Problem 3**

In [1]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])


sum_x_y = x + y
sum_v_w = v + w
print("Sum of x and y matrices: \n", sum_x_y, "\n")
print("Sum of v and w vectors: \n", sum_v_w, "\n")


diff_x_y = x - y
diff_v_w = v - w
print("Difference of x and y matrices: \n", diff_x_y, "\n")
print("Difference of v and w vectors: \n", diff_v_w, "\n")


prod_x_y = x * y
prod_v_w = v * w
print("Element-wise product of x and y matrices: \n", prod_x_y, "\n")
print("Element-wise product of v and w vectors: \n", prod_v_w, "\n")


sqr_x = np.square(x)
sqr_y = np.square(y)
sqr_v = np.square(v)
sqr_w = np.square(w)
print("Square of x matrix: \n", sqr_x, "\n")
print("Square of y matrix: \n", sqr_y, "\n")
print("Square of v vector: \n", sqr_v, "\n")
print("Square of w vector: \n", sqr_w, "\n")


dot_x_y = np.dot(x, y)
dot_v_w = np.dot(v, w)
print("Dot product of x and y matrices: \n", dot_x_y, "\n")
print("Dot product of v and w vectors: \n", dot_v_w, "\n")


Sum of x and y matrices: 
 [[ 6  8]
 [10 13]] 

Sum of v and w vectors: 
 [20 22] 

Difference of x and y matrices: 
 [[-4 -4]
 [-4 -3]] 

Difference of v and w vectors: 
 [-2 -2] 

Element-wise product of x and y matrices: 
 [[ 5 12]
 [21 40]] 

Element-wise product of v and w vectors: 
 [ 99 120] 

Square of x matrix: 
 [[ 1  4]
 [ 9 25]] 

Square of y matrix: 
 [[25 36]
 [49 64]] 

Square of v vector: 
 [ 81 100] 

Square of w vector: 
 [121 144] 

Dot product of x and y matrices: 
 [[19 22]
 [50 58]] 

Dot product of v and w vectors: 
 219 



In [3]:
import numpy as np
import time

# 1. Element-wise Addition
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]
arr1 = np.array(list1)
arr2 = np.array(list2)

# Python Lists
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()
print("Time taken for element-wise addition using Python Lists: ", end_time - start_time, "seconds\n")

# NumPy Arrays
start_time = time.time()
array_sum = arr1 + arr2
end_time = time.time()
print("Time taken for element-wise addition using NumPy Arrays: ", end_time - start_time, "seconds\n")

# 2. Element-wise Multiplication
# Python Lists
start_time = time.time()
list_prod = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()
print("Time taken for element-wise multiplication using Python Lists: ", end_time - start_time, "seconds\n")

# NumPy Arrays
start_time = time.time()
array_prod = arr1 * arr2
end_time = time.time()
print("Time taken for element-wise multiplication using NumPy Arrays: ", end_time - start_time, "seconds\n")

# 3. Dot Product
# Python Lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()
print("Time taken for dot product using Python Lists: ", end_time - start_time, "seconds\n")

# NumPy Arrays
start_time = time.time()
dot_product_array = np.dot(arr1, arr2)
end_time = time.time()
print("Time taken for dot product using NumPy Arrays: ", end_time - start_time, "seconds\n")

# 4. Matrix Multiplication
matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]
numpy_matrix1 = np.array(matrix1)
numpy_matrix2 = np.array(matrix2)

# Python Lists
start_time = time.time()
matrix_result = [[sum(a * b for a, b in zip(matrix1_row, matrix2_col)) for matrix2_col in zip(*matrix2)] for matrix1_row in matrix1]
end_time = time.time()
print("Time taken for matrix multiplication using Python Lists: ", end_time - start_time, "seconds\n")

# NumPy Arrays
start_time = time.time()
numpy_matrix_result = np.dot(numpy_matrix1, numpy_matrix2)
end_time = time.time()
print("Time taken for matrix multiplication using NumPy Arrays: ", end_time - start_time, "seconds\n")


Time taken for element-wise addition using Python Lists:  0.14768266677856445 seconds

Time taken for element-wise addition using NumPy Arrays:  0.005029201507568359 seconds

Time taken for element-wise multiplication using Python Lists:  0.16429877281188965 seconds

Time taken for element-wise multiplication using NumPy Arrays:  0.004596233367919922 seconds

Time taken for dot product using Python Lists:  0.15934157371520996 seconds

Time taken for dot product using NumPy Arrays:  0.0020761489868164062 seconds

Time taken for matrix multiplication using Python Lists:  208.2992136478424 seconds

Time taken for matrix multiplication using NumPy Arrays:  1.4402155876159668 seconds

